from flask import Flask, render_template, request, Response
from analyzer import analyze_logs

app = Flask(__name__)


@app.route("/", methods=["GET", "POST"])
def dashboard():

    results = None

    if request.method == "POST":

        file = request.files["logfile"]

        if file:

            logs = file.read().decode("utf-8").splitlines()

            results = analyze_logs(logs)

    return render_template("dashboard.html", results=results)


@app.route("/download")
def download_report():

    report = """
SOC Sentinel Report
===================

This report was generated by SOC Sentinel.

The uploaded log file has been analyzed successfully.

Thank you for using SOC Sentinel.
"""

    return Response(
        report,
        mimetype="text/plain",
        headers={
            "Content-Disposition": "attachment;filename=SOC_Report.txt"
        },
    )


if __name__ == "__main__":
    app.run(debug=True)